### ISSUE TITLE
Encounter "type=Einrichtungskontakt"

### ISSUE THREAD

**Issue by quastkj** [medizininformatik-initiative/Projectathon7-VHF-DataExtraction#3]
We have not included any encounters because of "type=Einrichtungskontakt".
Is it okay to delete this filter in order to also have encounters in the result?

**Comment by juliangruendner** [comment]
@quastkj  - i think it should be ok to delete this filter - but please be aware that in this case all encounters for the selected patients will be exported

**Comment by quastkj** [comment]
Thank you. It has just been confirmed that there are only "Einrichtungskontakt" in our data at the moment, so the adjustment should not be a problem.
