### ISSUE TITLE
Error in last Step - Bundleing

### ISSUE THREAD

**Issue by Tim-Steinbach-UKB** [medizininformatik-initiative/Projectathon7-VHF-DataExtraction#4]
Hi Julian,

we have a Problem in the last step with "build-transaction-bundle.py"-Script.
Se following Error-Output. Maybe you have a hint?

mii-data-extraction_1  | Begin creation of extraction transfer bundle...
mii-data-extraction_1  | Traceback (most recent call last):
mii-data-extraction_1  |   File "/opt/data-extraction/build-transaction-bundle.py", line 82, in <module>
mii-data-extraction_1  |     existing_doc_ref_id = get_existing_doc_ref(project_ident)
mii-data-extraction_1  |   File "/opt/data-extraction/build-transaction-bundle.py", line 72, in get_existing_doc_ref
mii-data-extraction_1  |     resp = requests.get(fhir_query, auth=HTTPBasicAuth(fhir_user, fhir_pw), proxies=proxies_fhir)
mii-data-extraction_1  |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
mii-data-extraction_1  |     return request('get', url, params=params, **kwargs)
mii-data-extraction_1  |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
mii-data-extraction_1  |     return session.request(method=method, url=url, **kwargs)
mii-data-extraction_1  |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
mii-data-extraction_1  |     resp = self.send(prep, **send_kwargs)
mii-data-extraction_1  |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 640, in send
mii-data-extraction_1  |     adapter = self.get_adapter(url=request.url)
mii-data-extraction_1  |   File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 731, in get_adapter
mii-data-extraction_1  |     raise InvalidSchema("No connection adapters were found for '%s'" % url)
mii-data-extraction_1  | requests.exceptions.InvalidSchema: No connection adapters were found for '/DocumentReference?identifier=http://medizininformatik-initiative.de/sid/project-identifier|"NT-proBNP"'
mii-data-extraction_1  | Finished creation of extraction transfer bundle...

**Comment by juliangruendner** [comment]
@Tim-Steinbach-UKB  did u set the env variables for the SHARE_FHIR Server:
MII_DATA_EXTRACTION_SHARE_FHIR_BASE_URL=http://fhir-server-share:8080/fhir
MII_DATA_EXTRACTION_SHARE_FHIR_USER=
MII_DATA_EXTRACTION_SHARE_FHIR_PW=
MII_DATA_EXTRACTION_SHARE_FHIR_TOKEN=
MII_DATA_EXTRACTION_SHARE_FHIR_PROXY_HTTP=
MII_DATA_EXTRACTION_SHARE_FHIR_PROXY_HTTPS=

note that the share fhir server env vars have to be filled out even if it is the same as the one where the data is extracted from

**Comment by wetret** [comment]
Hi Tim,

it does not solve your problem, but I just saw that you are using the wrong project identifier. Please change in the .env file the value of the parameter `MII_DATA_EXTRACTION_PROJ_IDENT` from `NT-proBNP` to `VHF-MI-2-zentral`. Without the correct project identifier, the DSF process will not find the data to transmit.

Cheers and have a nice weekend.

**Comment by Tim-Steinbach-UKB** [comment]
Combination of both answers worked.
Had to change to "VHF-MI-2-zentral" and set "MII_DATA_EXTRACTION_SHARE_FHIR_BASE_URL". Thanks a lot.

Have a nice Weekend
